export const PROTOCOL_VERSION = 1;
export const FRAME_HEADER_BYTES = 4;
export const DEFAULT_MAX_FRAME_SIZE = 64 * 1024;
export const DEFAULT_MAX_QUEUED_BYTES = 256 * 1024;

export enum PacketType { HELLO = 1, WELCOME = 2, DATA = 3, BATCH = 4, COMMAND = 5, ACK = 6, PING = 7, PONG = 8, ERROR = 9, DISCONNECT = 10 }
export enum FrameFlag { HAS_TIMESTAMP = 1 }
export enum ValueType { BOOL = 1, INT8 = 2, UINT8 = 3, INT16 = 4, UINT16 = 5, INT32 = 6, UINT32 = 7, INT64 = 8, UINT64 = 9, FLOAT32 = 10, FLOAT64 = 11, STRING = 12, BYTES = 13 }
export enum ErrorCode { UNSUPPORTED_VERSION = 1, AUTH_FAILED = 2, MALFORMED_FRAME = 3, FRAME_TOO_LARGE = 4, INVALID_PACKET = 5, INVALID_STATE = 6, UNSUPPORTED_TYPE = 7, HANDSHAKE_TIMEOUT = 8, SLOW_PEER = 9 }
export enum AckStatus { OK = 0, REJECTED = 1, UNSUPPORTED = 2, FAILED = 3 }
