import { ErrorCode, FrameFlag, PacketType, ValueType } from '../constants.js';
import type { Frame, Hello, Packet, RlpValue, Sample } from '../types.js';
import { RlpError } from '../types.js';

class Reader { constructor(private readonly b:Buffer, private p=0) {} get left():number{return this.b.length-this.p;} u8(){this.need(1);return this.b[this.p++];} u16(){this.need(2);const n=this.b.readUInt16BE(this.p);this.p+=2;return n;} u32(){this.need(4);const n=this.b.readUInt32BE(this.p);this.p+=4;return n;} i64(){this.need(8);const n=this.b.readBigInt64BE(this.p);this.p+=8;return n;} take(n:number){this.need(n);const x=this.b.subarray(this.p,this.p+n);this.p+=n;return x;} lp8(){return this.take(this.u8()).toString('utf8');} lp16(){return this.take(this.u16());} done(){if(this.left) throw new RlpError(ErrorCode.INVALID_PACKET,'trailing packet bytes');} private need(n:number){if(n>this.left)throw new RlpError(ErrorCode.INVALID_PACKET,'truncated packet');} }
function type(n:number):ValueType { if(n < ValueType.BOOL || n > ValueType.BYTES)throw new RlpError(ErrorCode.UNSUPPORTED_TYPE,`value type ${n}`);return n as ValueType; }
function value(r:Reader,t:ValueType):RlpValue { switch(t){case ValueType.BOOL:{const x=r.u8();if(x>1)throw new RlpError(ErrorCode.INVALID_PACKET,'invalid bool');return x===1;}case ValueType.INT8:return r.take(1).readInt8();case ValueType.UINT8:return r.u8();case ValueType.INT16:return r.take(2).readInt16BE();case ValueType.UINT16:return r.u16();case ValueType.INT32:return r.take(4).readInt32BE();case ValueType.UINT32:return r.u32();case ValueType.INT64:return r.i64();case ValueType.UINT64:{const x=r.take(8);return x.readBigUInt64BE();}case ValueType.FLOAT32:return r.take(4).readFloatBE();case ValueType.FLOAT64:return r.take(8).readDoubleBE();case ValueType.STRING:{const b=r.lp16();const text=b.toString('utf8');if(Buffer.from(text,'utf8').compare(b)!==0)throw new RlpError(ErrorCode.INVALID_PACKET,'invalid UTF-8');return text;}case ValueType.BYTES:return r.lp16();} }
function sample(r:Reader, flags:number, timestampAllowed=true):Sample { if(flags & ~FrameFlag.HAS_TIMESTAMP)throw new RlpError(ErrorCode.INVALID_PACKET,'unknown sample flag');const channel=r.u16(), valueType=type(r.u8());const timestamp=(flags&FrameFlag.HAS_TIMESTAMP)?(timestampAllowed?r.i64():(()=>{throw new RlpError(ErrorCode.INVALID_PACKET,'timestamp not allowed');})()):undefined;return {channel,valueType,value:value(r,valueType),...(timestamp===undefined?{}:{timestamp})}; }
export function decodePacket(f:Frame):Packet { const r=new Reader(f.payload); switch(f.type){
  case PacketType.HELLO:{if(f.flags)throw new RlpError(ErrorCode.INVALID_PACKET,'HELLO flags');const hello:Hello={version:r.u8(),deviceId:r.lp8(),credential:r.lp16(),capabilities:r.lp16()};r.done();return{type:f.type,hello};}
  case PacketType.WELCOME:{if(f.flags)throw new RlpError(ErrorCode.INVALID_PACKET,'WELCOME flags');const welcome={version:r.u8(),capabilities:r.lp16()};r.done();return{type:f.type,welcome};}
  case PacketType.DATA:{const s=sample(r,f.flags);r.done();return{type:f.type,sample:s};}
  case PacketType.BATCH:{if(f.flags)throw new RlpError(ErrorCode.INVALID_PACKET,'BATCH flags');const n=r.u16();const samples:Sample[]=[];for(let i=0;i<n;i++)samples.push(sample(r,r.u8()));r.done();return{type:f.type,samples};}
  case PacketType.COMMAND:{if(f.flags)throw new RlpError(ErrorCode.INVALID_PACKET,'COMMAND flags');const id=r.u32(),s=sample(r,0,false);r.done();return{type:f.type,command:{id,...s}};}
  case PacketType.ACK:{if(f.flags)throw new RlpError(ErrorCode.INVALID_PACKET,'ACK flags');const ack={id:r.u32(),status:r.u8()};r.done();return{type:f.type,ack};}
  case PacketType.PING:case PacketType.PONG:{if(f.flags)throw new RlpError(ErrorCode.INVALID_PACKET,'heartbeat flags');const nonce=r.u32();r.done();return{type:f.type,nonce};}
  case PacketType.ERROR:{if(f.flags)throw new RlpError(ErrorCode.INVALID_PACKET,'ERROR flags');const error={code:r.u16() as ErrorCode,message:r.lp8()};r.done();return{type:f.type,error};}
  case PacketType.DISCONNECT:{if(f.flags)throw new RlpError(ErrorCode.INVALID_PACKET,'DISCONNECT flags');const code=r.u16() as ErrorCode;r.done();return{type:f.type,code};}
  default:throw new RlpError(ErrorCode.INVALID_PACKET,`unknown packet type ${f.type}`);
 } }
