import { fork } from 'node:child_process'; import { mkdir, writeFile } from 'node:fs/promises'; import { join } from 'node:path'; import { connect, type Socket } from 'node:net'; import { monitorEventLoopDelay, performance } from 'node:perf_hooks';
import { AckStatus, FrameDecoder, PacketType, PROTOCOL_VERSION, ValueType, decodePacket, encodeAck, encodeBatch, encodeData, encodeHello, type Packet, type Sample } from '../../index.js';

type Profile='idle'|'environmental'|'energy'|'relay'|'offline'; type Mode='normal'|'burst'|'random-fragment'|'byte';
interface Config {devices:number;durationMs:number;profile:Profile;mode:Mode;seed:number;commandRate:number;slowDevices:number;maxQueue:number;batch:boolean;output:string;}
function arg(name:string,fallback:string){const i=process.argv.indexOf(`--${name}`);return i<0?fallback:process.argv[i+1]??fallback;}function duration(s:string){const n=Number.parseFloat(s);return s.endsWith('m')?n*60000:s.endsWith('s')?n*1000:n*1000;}
const config:Config={devices:Number(arg('devices','1000')),durationMs:duration(arg('duration','60s')),profile:arg('profile','environmental') as Profile,mode:arg('mode','normal') as Mode,seed:Number(arg('seed','42')),commandRate:Number(arg('commands','0')),slowDevices:Number(arg('slow-devices','0')),maxQueue:Number(arg('max-queue','262144')),batch:arg('batch','true')!=='false',output:arg('output','bench-results')};
if(!Number.isInteger(config.devices)||config.devices<1||!['idle','environmental','energy','relay','offline'].includes(config.profile)||!['normal','burst','random-fragment','byte'].includes(config.mode))throw new Error('invalid fleet arguments');
let randomState=config.seed>>>0;const random=()=>((randomState=(randomState*1664525+1013904223)>>>0)/4294967296);const jitter=(base:number,pct=.1)=>base*(1-pct+random()*pct*2);
const profileInterval:Record<Profile,number>={idle:0,environmental:5000,energy:1000,relay:10000,offline:5000}; const errorKinds=new Map<string,number>();
class Device { socket?:Socket; decoder=new FrameDecoder(); active=false; nextDue=0; reconnectAt=0; sent=0; samples=0; bytes=0; reconnects=0; errors=0; private welcomed=false; constructor(readonly id:number,private readonly port:number,readonly profile:Profile,readonly slow:boolean){} connect(){const s=this.socket=connect(this.port,'127.0.0.1');s.on('connect',()=>this.write(encodeHello({version:PROTOCOL_VERSION,deviceId:`fleet-${this.id}`,credential:Buffer.alloc(0),capabilities:Buffer.alloc(0)})));s.on('data',b=>{try{for(const p of this.decoder.push(b).map(decodePacket))this.packet(p);}catch(error){this.recordError(error);s.destroy();}});s.on('close',()=>{this.active=false;if(!stopping)this.reconnectAt=performance.now()+jitter(Math.min(30000,1000*Math.pow(2,Math.min(5,this.reconnects++))));});s.on('error',error=>this.recordError(error));}
 private recordError(error:unknown){this.errors++;const key=error instanceof Error?`${error.name}:${error.message}`:'unknown';errorKinds.set(key,(errorKinds.get(key)??0)+1);}
 private packet(p:Packet){if(p.type===PacketType.WELCOME){const reconnected=this.welcomed;this.welcomed=true;this.active=true;this.reconnects=0;const interval=profileInterval[this.profile];this.nextDue=interval?performance.now()+random()*interval:0;if(reconnected&&this.profile==='offline')for(let n=0;n<10;n++)this.telemetry();if(this.slow)this.socket?.pause();}else if(p.type===PacketType.COMMAND){this.write(encodeAck({id:p.command.id,status:AckStatus.OK}));ackReceived++;}}
 tick(now:number){if(!this.socket&&!this.reconnectAt)this.connect();if(!this.active){if(this.reconnectAt&&now>=this.reconnectAt){this.reconnectAt=0;this.connect();}return;}if(this.profile==='offline'&&now>12000&&random()<0.0002){this.socket!.destroy();return;}if(this.nextDue&&now>=this.nextDue){this.telemetry();const every=profileInterval[this.profile];this.nextDue=every?now+jitter(every):0;}}
 private telemetry(){if(this.profile==='energy'&&!config.batch){for(let c=1;c<=8;c++){const frame=encodeData({channel:c,valueType:ValueType.FLOAT32,value:random()*240});this.write(frame);this.sent++;this.samples++;this.bytes+=frame.length;}return;}let frame:Buffer;if(this.profile==='energy'){const samples:Sample[]=[];for(let c=1;c<=8;c++)samples.push({channel:c,valueType:ValueType.FLOAT32,value:random()*240});frame=encodeBatch(samples);this.samples+=8;}else {frame=encodeData({channel:1,valueType:ValueType.FLOAT32,value:20+random()*10});this.samples++;}this.write(frame);this.sent++;this.bytes+=frame.length;}
 private write(frame:Buffer){if(!this.socket||this.socket.destroyed)return;if(config.mode==='byte'){for(const b of frame)this.socket.write(Buffer.from([b]));}else if(config.mode==='random-fragment'){for(let p=0;p<frame.length;){const n=Math.min(frame.length-p,1+Math.floor(random()*64));this.socket.write(frame.subarray(p,p+n));p+=n;}}else this.socket.write(frame);}
 stop(){this.socket?.destroy();}}
let stopping=false,ackReceived=0;const server=fork(new URL('./server.js',import.meta.url),[],{env:{...process.env,RLP_FLEET_PORT:'0',RLP_FLEET_COMMAND_RATE:String(config.commandRate),RLP_FLEET_MAX_QUEUE:String(config.maxQueue)},stdio:['ignore','ignore','ignore','ipc']});const serverMetrics:unknown[]=[];let port=0;
await new Promise<void>((resolve,reject)=>{server.once('message',(m:{kind:string;port:number})=>{if(m.kind==='ready'){port=m.port;resolve();}});server.once('error',reject);});
const devices=Array.from({length:config.devices},(_,i)=>new Device(i,port,config.profile,i<config.slowDevices));const simDelay=monitorEventLoopDelay({resolution:1});simDelay.enable();const simStart=performance.now(), simBaseline=process.memoryUsage();let lastCpu=process.cpuUsage();const simulatorMetrics:unknown[]=[];
server.on('message',(m:{kind:string;metrics?:unknown})=>{if(m.kind==='metrics')serverMetrics.push(m.metrics);});
for(const d of devices){d.reconnectAt=config.mode==='burst'?0:random()*1000;}const scheduler=setInterval(()=>{const now=performance.now();for(const d of devices)d.tick(now);},25);const metricTimer=setInterval(()=>{const cpu=process.cpuUsage(lastCpu);lastCpu=process.cpuUsage();simulatorMetrics.push({atMs:+(performance.now()-simStart).toFixed(1),active:devices.filter(d=>d.active).length,framesSent:devices.reduce((n,d)=>n+d.sent,0),expectedSamples:devices.reduce((n,d)=>n+d.samples,0),bytes:devices.reduce((n,d)=>n+d.bytes,0),errors:devices.reduce((n,d)=>n+d.errors,0),errorKinds:Object.fromEntries(errorKinds),reconnects:devices.reduce((n,d)=>n+d.reconnects,0),acksFromCommands:ackReceived,rss:process.memoryUsage().rss,heapUsed:process.memoryUsage().heapUsed,heapTotal:process.memoryUsage().heapTotal,cpuUserUs:cpu.user,cpuSystemUs:cpu.system,eventLoopMs:{p50:simDelay.percentile(50)/1e6,p95:simDelay.percentile(95)/1e6,p99:simDelay.percentile(99)/1e6,mean:simDelay.mean/1e6}});simDelay.reset();},1000);
await new Promise(r=>setTimeout(r,config.durationMs));stopping=true;clearInterval(scheduler);clearInterval(metricTimer);for(const d of devices)d.stop();server.send('stop');await new Promise<void>(r=>server.once('exit',()=>r()));
const now=new Date().toISOString().replace(/[:.]/g,'-');await mkdir(config.output,{recursive:true});const result={schema:1,config:{...config,durationMs:config.durationMs,plainTcp:true,topology:'server child process and simulator parent process on localhost'},environment:{node:process.version,platform:process.platform,arch:process.arch,cpus:await import('node:os').then(x=>x.cpus().map(c=>c.model)),simulatorBaseline:simBaseline},simulatorMetrics,serverMetrics};const path=join(config.output,`${now}-${config.profile}-${config.devices}.json`);await writeFile(path,JSON.stringify(result));console.log(JSON.stringify({result:path,config,simulatorLast:simulatorMetrics.at(-1),serverLast:serverMetrics.at(-1)},null,2));
